# Generated by Django 3.2.13 on 2022-05-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_credit', models.PositiveIntegerField()),
                ('r_inter', models.FloatField(max_length=5)),
                ('a_annuity', models.PositiveIntegerField()),
                ('r_repay', models.FloatField(max_length=5)),
                ('n_credit_term', models.PositiveIntegerField()),
            ],
        ),
    ]
